import React from "react"

// import './admin-globals.scss'
import { redirect } from "next/navigation";
import { Metadata } from "next";
import { getServerSession } from "next-auth";
import { nextAuthOptions } from "../(api)/api/auth/[...nextauth]/authOptions";

export const metadata: Metadata = {
    title: 'Admin',
    description: 'Generated by create next app',
}

export default async function AdminLayout({
    children,
    params,
}: {
    children: React.ReactNode,
    params: {
        slug: string[],
        searchParams: {
            [key: string]: string;
        }
    },
}) {
    const session = await getServerSession(nextAuthOptions);

    // @ts-ignore
    if (!session || session.user?.role < 2) {
        redirect(`/`);
    }
    return (
        <html lang="en">
            <body>{children}</body>
        </html>
    )
}